# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calification',
            old_name='calification_value',
            new_name='rating',
        ),
    ]
