# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating_engine', '0002_auto_20161110_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='calification',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
